{
 "title": "OpenTTD economy",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Rate of change in bank balance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    { "expr": "deriv(openttd_money[15m])" }
   ]
  },
  {
   "title": "Debt",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "currencyGBP" }
   ],
   "targets": [
    { "expr": "openttd_loan" }
   ]
  },
  {
   "title": "Bank balance",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "currencyGBP" }
   ],
   "targets": [
    {
     "expr": "sum(openttd_money-openttd_loan) by (company_id)"
    }
   ]
  },
  {
   "title": "Rate of change of company value",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(deriv(openttd_value[30m])) by (company_id)"
    }
   ]
  },
  {
   "title": "Company value",
   "type": "graph",
   "gridPos": { "h": 23, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "currencyGBP" }
   ],
   "targets": [
    {
     "expr": "sum(openttd_value) by (company_id)"
    }
   ]
  },
  {
   "title": "Predicted company value one hour from now (log base 2)",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "currencyGBP" }
   ],
   "targets": [
    {
     "expr": "sum(predict_linear(openttd_value[20m], 60*60)) by (company_id)"
    }
   ]
  },
  {
   "title": "Total vehicles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openttd_lorry_count + openttd_train_count + openttd_bus_count + openttd_ship_count + openttd_plane_count) by (company_id)"
    }
   ]
  },
  {
   "title": "Total stations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openttd_train_station_count + openttd_bus_station_count + openttd_ship_station_count + openttd_plane_station_count + openttd_lorry_station_count) by (company_id)"
    }
   ]
  },
  {
   "title": "Income",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "openttd_income" }
   ]
  }
 ]
}